name: Build Kernel (With KSU)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v3
      with:
        repository: awakened1712/android_kernel_oneplus_sm8350
        ref: lineage-20
        path: sm8350
        fetch-depth: 100

    - name: Checkout gcc toolchain
      uses: actions/checkout@v3
      with:
        repository: mvaisakh/gcc-arm64
        path: toolchain

    - name: Checkout patches
      uses: actions/checkout@v3
      with:
        ref: build
        path: patches

    - name: Apply patches
      run: |
        cd sm8350
        git submodule add https://github.com/tiann/KernelSU.git
        git apply ../patches/ksu.patch
        git submodule update --init --recursive

    - name: Android kernel build
      run: |
        sudo apt install libdebuginfod-dev
        export PATH="$(pwd)/toolchain/bin:${PATH}"
        cd sm8350
        bash build.sh
        git log --no-decorate --oneline -n 100 > out/ak3/ChangeLog.txt

    - name: Upload final output
      uses: actions/upload-artifact@v3
      with:
        name: release-ksu
        path: |
          sm8350/out/ak3/ChangeLog.txt
          sm8350/out/ak3/*.zip
